---
- name: Deinstall Oracle Home if unused and safe
  hosts: db_servers
  become: yes
  vars:
    oracle_home: "{{ oracle_home | default('') }}"

  tasks:

    - name: Fail if ORACLE_HOME is not provided
      ansible.builtin.fail:
        msg: "ORACLE_HOME is not set. Use -e 'oracle_home=/path/to/home'"
      when: oracle_home == ""

    - name: Check for running processes using ORACLE_HOME
      ansible.builtin.shell: "ps -ef | grep -v grep | grep '{{ oracle_home }}'"
      register: home_process_check
      ignore_errors: true
      changed_when: false

    - name: Fail if running processes are found using ORACLE_HOME
      ansible.builtin.fail:
        msg: |
          Oracle processes are still using {{ oracle_home }}:
          {{ home_process_check.stdout_lines }}
      when: home_process_check.stdout != ""

    - name: Check if ORACLE_HOME exists in /etc/oratab
      ansible.builtin.shell: "grep -F '{{ oracle_home }}' /etc/oratab"
      register: oratab_check
      ignore_errors: true
      changed_when: false

    - name: Fail if ORACLE_HOME is still referenced in oratab
      ansible.builtin.fail:
        msg: "ORACLE_HOME {{ oracle_home }} still appears in /etc/oratab"
      when: oratab_check.stdout != ""

    - name: Check if deinstall script exists
      ansible.builtin.stat:
        path: "{{ oracle_home }}/deinstall/deinstall"
      register: deinstall_script

    - name: Fail if deinstall script is missing
      ansible.builtin.fail:
        msg: "Deinstall script not found at {{ oracle_home }}/deinstall/deinstall"
      when: not deinstall_script.stat.exists

    - name: Run checkonly to generate response file
      ansible.builtin.shell: |
        "{{ oracle_home }}/deinstall/deinstall" -silent -checkonly
      args:
        chdir: "{{ oracle_home }}/deinstall"
      register: checkonly_output
      environment:
        ORACLE_HOME: "{{ oracle_home }}"
      changed_when: false

    - name: Extract response file path using a more precise regex pattern
      ansible.builtin.set_fact:
        rsp_file_matches: >-
          {{ checkonly_output.stdout_lines | map('regex_findall', "generated: '(.*?\\.rsp)'") | list | flatten }}

    - name:
        Debug: Show all found response file matches
      ansible.builtin.debug:
        msg: "Found response files: {{ rsp_file_matches }}"

    - name: Set deinstall_response_file if a match is found
      ansible.builtin.set_fact:
        deinstall_response_file: "{{ rsp_file_matches[0] }}"
      when: rsp_file_matches | length > 0

    - name:
        Debug: Show selected response file
      ansible.builtin.debug:
        msg: "Selected response file: {{ deinstall_response_file }}"

    - name: Check if response file exists
      ansible.builtin.stat:
        path: "{{ deinstall_response_file }}"
      register: rsp_file_check
      when: deinstall_response_file is defined

    - name: Fail if response file is not found
      ansible.builtin.fail:
        msg: "Response file was not found: {{ deinstall_response_file }}"
      when: deinstall_response_file is not defined or not rsp_file_check.stat.exists

    - name: Run Oracle deinstall using generated response file
      ansible.builtin.shell: >
        "{{ oracle_home }}/deinstall/deinstall" -silent -paramfile "{{ deinstall_response_file }}"
      args:
        chdir: "{{ oracle_home }}/deinstall"
      register: deinstall_output
      environment:
        ORACLE_HOME: "{{ oracle_home }}"
      changed_when: "'Successfully deinstalled' in deinstall_output.stdout"

    - name: Print deinstall output
      ansible.builtin.debug:
        var: deinstall_output.stdout_lines
