- name: Collect PostgreSQL Configuration Settings
  ansible.builtin.command:
    cmd: "psql -U postgres -c 'SHOW ALL;'"
  register: postgres_settings
  changed_when: false

- name: Collect PostgreSQL User Roles
  ansible.builtin.command:
    cmd: "psql -U postgres -c '\\du'"
  register: postgres_user_roles
  changed_when: false

- name: Collect PostgreSQL Active Extensions
  ansible.builtin.command:
    cmd: "psql -U postgres -c '\\dx'"
  register: postgres_extensions
  changed_when: false

- name: Collect PostgreSQL Database Configurations
  ansible.builtin.command:
    cmd: "psql -U postgres -c '\\l+'"
  register: postgres_db_config
  changed_when: false

- name: Save PostgreSQL configuration to file
  ansible.builtin.copy:
    content: |
      Configuration Settings:
      {{ postgres_settings.stdout }}

      User Roles:
      {{ postgres_user_roles.stdout }}

      Active Extensions:
      {{ postgres_extensions.stdout }}

      Database Configurations:
      {{ postgres_db_config.stdout }}
    dest: "/tmp/current_postgres_config.txt"

