- name: Compare Oracle configuration with baseline
  ansible.builtin.command:
    cmd: "diff /tmp/current_oracle_config.txt {{ playbook_dir }}/baselines/oracle_baseline.txt"
  register: oracle_diff
  ignore_errors: yes
  when: "'oracle_db_servers' in group_names"

- name: Compare PostgreSQL configuration with baseline
  ansible.builtin.command:
    cmd: "diff /tmp/current_postgres_config.txt {{ playbook_dir }}/baselines/postgres_baseline.txt"
  register: postgres_diff
  ignore_errors: yes
  when: "'postgres_servers' in group_names"

