---
- name: Oracle Services Discovery Playbook
  hosts: oracle_servers
  become: yes
  become_user: oracle
  gather_facts: yes
  vars:
    oracle_output_dir: "/tmp/oracle_discovery"
    report_destination: "/var/www/html/oracle_report.html"
    timestamp: "{{ ansible_date_time.date }}_{{ ansible_date_time.time }}"
    oratab_path: "/etc/oratab"
    # Locations of Python scripts on control node
    scripts_dir: "./scripts"
    # Python virtual environment settings
    python_venv: "/tmp/oracle_discovery/venv"
    python_bin: "python3"

  tasks:
    - name: Create output directory
      file:
        path: "{{ oracle_output_dir }}"
        state: directory
        mode: '0755'
      become: yes
      become_user: root

    - name: Check if python3-venv is installed
      package:
        name: python3-venv
        state: present
      become: yes
      become_user: root
      register: venv_install
      ignore_errors: yes

    - name: Install python3-venv if it's not installed
      package:
        name: python3-venv
        state: present
      become: yes
      become_user: root
      when: venv_install is failed
      ignore_errors: yes

    - name: Create Python virtual environment
      pip:
        name: pip
        state: latest
        virtualenv: "{{ python_venv }}"
        virtualenv_command: "{{ python_bin }} -m venv"
      become: yes
      become_user: oracle

    - name: Install required Python packages in virtual environment
      pip:
        name: oracledb
        state: present
        virtualenv: "{{ python_venv }}"
      become: yes
      become_user: oracle

    - name: Copy Python scripts to target hosts
      copy:
        src: "{{ scripts_dir }}/{{ item }}"
        dest: "{{ oracle_output_dir }}/{{ item }}"
        mode: '0755'
      loop:
        - check_oracle_db.py
        - check_oracle_listener.py
        - discover_listeners.py

    - name: Check if oratab file exists
      stat:
        path: "{{ oratab_path }}"
      register: oratab_file

    - name: Fail if oratab file doesn't exist
      fail:
        msg: "Oracle oratab file not found at {{ oratab_path }}"
      when: not oratab_file.stat.exists

    - name: Parse oratab file
      shell: grep -v "^#" {{ oratab_path }} | grep -v "^$" | awk -F: '{print $1":"$2}'
      register: oratab_entries
      changed_when: false

    - name: Process each Oracle SID from oratab
      include_tasks: check_sid.yml
      loop: "{{ oratab_entries.stdout_lines }}"
      loop_control:
        loop_var: sid_entry

    - name: Create HTML report from template
      template:
        src: oracle_report.html.j2
        dest: "{{ report_destination }}"
      become: yes
      become_user: root

    - name: Set permissions on HTML report
      file:
        path: "{{ report_destination }}"
        mode: '0644'
      become: yes
      become_user: root

    - name: Show report location
      debug:
        msg: "Oracle services discovery report has been generated at {{ report_destination }}"

    - name: Clean up Python virtual environment (optional)
      file:
        path: "{{ python_venv }}"
        state: absent
      become: yes
      become_user: oracle
      when: false  # Set to true if you want to clean up after execution